export const ADMIN_ROUTE = '/profile/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const PRODUCT_ROUTE = '/shop'
export const PROFILE_PAGE = '/profile'